add bash script

diff --git a/bash/touchpad-xinput b/bash/touchpad-xinput
--- a/bash/touchpad-xinput
+++ b/bash/touchpad-xinput
@@ -12,3 +12,30 @@ xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Edge Scrolling" 0 0 0
 
 
 # default: Synaptics Finger (268):	35 40 10
+
+
+
+#################################
+# bash script 
+#################################
+
+#!/bin/bash
+# start from ~/.config/lxsession/Lubuntu/autostart
+
+#Config touchpad to disable Edge Scrolling and reduce sensitivity
+xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Edge Scrolling" 0 0 0
+
+result=$?
+if [ $result -eq 0 ]; then 
+	xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Finger" 35 50 40
+else
+	echo "FAIL - Disable Edge Scrolling"
+	xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Finger" 35 50 40
+fi
+
+result=$?
+if [ $result -ne 0 ]; then 
+	echo "FAIL - Reduce sensitivity"
+fi
+
+#################################
